#!/usr/bin/env php
<?php

if (php_sapi_name() !== "cli")
    exit;

include_once "Lib/Util/helper.php";
include_once "Lib/Util/DotEnv.php";
include_once "Lib/Autoloader.php";

define("DIR", __DIR__);

$app = require_once "Lib\\Cli\\app.php";

$app->run($argv);
$app->getPrinter()->nl();
